apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service.utils.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service.utils.svc.cluster.local:9092"
        - name: KAFKA_LISTENERS 
          value: "PLAINTEXT://0.0.0.0:9092" 
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP 
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LOG_DIRS 
          value: "/var/lib/kafka/data" 
        volumeMounts: 
        - name: kafka-data 
          mountPath: /var/lib/kafka/data 
      volumes: 
      - name: kafka-data 
        emptyDir: {}
