apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
data:
  JWT_SECRET: c29tZXNoaXR0eWp3dHRva2VuaXNiZWluZ3VzZWQ=
  AWS_ACCESS_KEY_ID: QUtJQTZHQk1DVTdaSkxDUE9RT1A=
  AWS_SECRET_ACCESS_KEY: WDI4czlYWVEyWGNFN0RLdE1uZE42OVZmemZRN3p6S1BKUGVBdk94UA==
  AWS_S3_BUCKET_NAME: YXJwaXQtY2Fwc3RvbmUtczM=
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5kYXRhYmFzZS5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9qb2JzYXBw
