version: '3.8'

services:
  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - job-network
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - job-network
    
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  
    networks:
      - job-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=jobdatabase
    networks:
      - job-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  authService:
    build: 
      context: ./backend/authService
      dockerfile: Dockerfile
    container_name: authservice
    image: jobsapp-authservice-backend:v1
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://user:password123@mongo:27017/jobdatabase
      - JWT_SECRET=someshittyjwttokenisbeingused
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
    depends_on:
    - redis
    - kafka
    - mongo

  companyService:
    build: 
      context: ./backend/companyService
      dockerfile: Dockerfile
    container_name: companyservice
    image: jobsapp-companyservice-backend:v1
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://user:password123@mongo:27017/jobdatabase
      - JWT_SECRET=someshittyjwttokenisbeingused
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
    depends_on:
    - redis
    - kafka
    - mongo

  userService:
    build: 
      context: ./backend/userService
      dockerfile: Dockerfile
    container_name: userservice
    image: jobsapp-userservice-backend:v1
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://user:password123@mongo:27017/jobdatabase
      - JWT_SECRET=someshittyjwttokenisbeingused
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
    depends_on:
    - redis
    - kafka
    - mongo

networks:
  job-network:
    driver: bridge

volumes:
  mongo-data: