apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: arpit1605/jobsapp-userservice-backend:v1
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets 
              key: MONGO_URI
        - name: PORT
          value: "5001"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: REDIS_HOST
          value: "redis-service.database.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: AWS_S3_BUCKET_NAME
