apiVersion: v1
kind: Service
metadata:
  name: companyservice-service
  namespace: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP
