apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: arpit1605/jobsapp-authservice-backend:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service.database.svc.cluster.local:27017/jobsapp"
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: someshittyjwttokenisbeingused
        - name: REDIS_HOST
          value: "redis-service.database.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BROKERS
          value: "kafka-service.utils.svc.cluster.local:9092"